### ISSUE TITLE
0.17 changelog up to 0.17.0's API.

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#808]
0.17.0 changelog update at bottom

## Changes to existing

- [x] Changed LuaEntity::destroy() to accept a table of arguments. #811
- [x] Changed LuaEntity::revive() to accept a table of arguments. #811
- [x] Changed the player_used_capsule event so it's fired after the capsule item is consumed from the cursor. (Note: this should be fine as it previously returned the LuaItemPrototype and still does) N/A
- [x] Changed LuaEntity::splitter_filter, splitter_input_priority, and splitter_output_priority so they also work on ghosts. N/A
- [x] Changed LuaSurface::destroy_decoratives() to take filters similar to find_entities_filtered. N/A
- [x] Changed most LuaEntity properties/functions to also work on ghosts.N/A
- [x] Changed on_player_crafted_item item_stack to allow editing the stack before it's put into the player inventory. N/A
- [x] Changed LuaSurface::regenerate_entity()/regenerate_decorative() to treat "nil" as "all" for the autoplace list. #812
- [x] Renamed LuaEntity::get_infinity_filter(), set_infinity_filter(), and infinity_filters to get_infinity_container_filter(), N/A
- [x] set_infinity_container_filter(), and infinity_container_filters. N/A
- [x] Renamed on_canceled_deconstruction event to on_cancelled_deconstruction. N/A
- [x] Fixed the spelling of LuaForce::max_successful_attempts_per_tick_per_construction_queue. N/A
- [ ] LuaSurface::find_entities/filtered now accepts a zero sized bounding box as "find everything that collides with this point".
- [x] CustomSprite now scales to the size of the sprite if a manual size isn't defined.
- [x] LuaStyle::visible was removed and instead LuaGuiElement::visible is used. #813
- [x] Removed LuaSurface::get_tile_properties(). N/A
- [x] Added "loot" to the on_entity_died event.
- [x] on_player_built_tile is no longer certain to provide item or stack #816
- [x] Check if `serpent.block` works for int64 keys <https://forums.factorio.com/viewtopic.php?f=218&t=64019>

## New classes
https://lua-api.factorio.com/0.17.0-preview/LuaRendering.html
https://lua-api.factorio.com/0.17.0-preview/LuaAISettings.html
https://lua-api.factorio.com/0.17.0-preview/LuaFluidBoxPrototype.html
https://lua-api.factorio.com/0.17.0-preview/LuaRailPath.html

## New ents
Added a new entity type "infinity-pipe" that automatically adds/removes fluid from itself; similar to the infinity-chest. #809
Added a new entity type "heat-interface" that automatically sets its own temperature. #809
Added "speech-bubble" entity. 
Added highlight-box entity that can be passed a "bounding_box" or "source" entity parameter to display a highlight box around an area or entity.

## Concepts
Removed: Catalyst, InfinityFilter
Added: ScriptArea, ScriptPosition, Fluid, UpgradeFilter, InfinityContainerFilter, InfinityPipeFilter, HeatSetting, FluidBoxConnection, PathfindFlags, ForceSpecification, TechnologySpecification, ItemStackSpecification, EntityPrototypeSpecification, ItemPrototypeSpecification, CollisionMaskLayer, CursorBoxRenderType, ForceCondition and RenderLayer
Added GameViewSettings :: show_side_menu
Added GameViewSettings :: show_map_view_options

#### High Interest
Changed LuaEntity::destroy() to accept a table of arguments.
Changed LuaEntity::revive() to accept a table of arguments.
Renamed LuaEntity::get_infinity_filter(), set_infinity_filter(), and infinity_filters to get_infinity_container_filter(), set_infinity_container_filter(), and infinity_container_filters.
Added LuaEntity::clear_market_items().
Added LuaEntity::clone().
Added LuaEntity::crafting_speed read.
Added LuaEntity::create_build_effect_smoke.
Added LuaEntity::get_beam_source(), set_beam_source(), get_beam_target() and set_beam_target().
Added LuaEntity::inserter_filter_mode read/write.
Added LuaEntity::neighbour_bonus read.
Added LuaEntity::recipe_locked read/write for assembling machines.
Added LuaEntity::render_player read/write.
Added LuaEntity::render_to_forces read/write.
Added LuaEntity::status read. (https://lua-api.factorio.com/0.17.0-preview/defines.html#defines.entity_status)
Added optional create_build_effect_smoke parameter to LuaSurface::create_entity.

#### Medium interest
Changed LuaEntity::splitter_filter,and splitter_output_priority so they also work on ghosts.
Changed most LuaEntity properties/functions to also work on ghosts.
Added LuaEntity::ai_settings read.,get_fluid_contents(),insert_fluid(),remove_fluid(),splitter_input_priority
Added LuaEntity::drop_target/pickup_target write.
Added LuaEntity::get_fluid_count(),and clear_fluid_inside().
Added LuaEntity::silent_revive().

#### Low interest
Added LuaEntity::enable_logistics_while_moving read/write.
Added LuaEntity::get_health_ratio().
Added LuaEntity::get_infinity_pipe_filter() and set_infinity_pipe_filter().
Added LuaEntity::get_radius() and LuaEntityPrototype::radius read.
Added LuaEntity::ghost_has_flag().
Added LuaEntity::moving. Returns true if the unit is moving.
Added LuaEntity::neighbours support for power switches, wall-connectable entities, and reactors.
Added LuaEntity::pump_rail_target read.
Added LuaEntity::trains_in_block read.

## Rails
Added LuaTrain::path read.
Added LuaEntity::connected_rail read.
Added LuaTrain::max_forward_speed and max_backward_speed read.
Added LuaTrain::go_to_station().
Added LuaTrain::get_rails().

## AI Commands
Added "stop" AI command, which tells the unit to just stop moving where it is. Takes a "ticks_to_wait" parameter, after which it returns to normal.
Added ticks_to_wait parameter to wander ai command.
Added "pathfind_flags" parameter to "go_to_location" AI command.
Added "radius" and "wander_in_group" parameters to "wander" AI command.
Added "radius" parameter to "go_to_location" AI command.

## GUI
Added LuaGuiElement type "list-box".
LuaStyle::visible was removed and instead LuaGuiElement::visible is used.
Added LuaGuiElement::resize_to_sprite (read/write).
Added SpritePath::equipment.

## Controllers
Added a spectator controller type that can view anything but can't change anything.
Added "cutscene" controller. (Confirmed by Klonan to be available in MP)
Added editor controller

#### High interest
Changed the maximum number of surfaces from 255 to 4,294,967,295.
Added LuaSurface::clear().
Added LuaSurface::clone_area().
Added LuaSurface::clone_entities().
Added LuaSurface::find_decoratives_filtered().
Added LuaSurface::find_units().
Added LuaSurface::get_total_pollution().
Added LuaSurface::solar_power_multiplier read/write.
Added collision_mask to LuaSurface::count/find_entities_filtered.
Added optional parameters to LuaSurface::create_entity, LuaEntity::destroy and LuaEntity::revive to raise the associated script events.
Added optional render_player_index parameter for flying-text and simple-entities to LuaSurface::create_entity.
LuaSurface::find_entities/filtered now accepts a zero sized bounding box as "find everything that collides with this point".

#### Medium interest
Added LuaSurface::get_closest().
Added LuaSurface::get_map_exchange_string().
Added LuaSurface::request_path().

#### Low interest
Added LuaSurface::get_train_stops()
Added LuaSurface::deconstruct/cancel_deconstruct optional parameters skip_fog_of_war and item.
Added LuaSurface::get_starting_area_radius().
Added direction to LuaSurface::count/find_entities_filtered.

## Events
Added:
on_ai_command_completed
on_chunk_deleted
on_game_created_from_scenario
on_player_banned
on_player_fast_transferred
on_player_kicked
on_player_repaired_entity
on_player_toggled_alt_mode
on_player_unbanned
on_pre_chunk_deleted
on_pre_surface_cleared
on_rocket_launch_ordered.
on_surface_cleared
on_surface_renamed
on_train_schedule_changed
on_unit_added_to_group
on_unit_group_created
on_unit_removed_from_group
on_cancelled_upgrade
on_cutscene_waypoint_reached
on_entity_cloned
on_entity_spawned
on_marked_for_upgrade
on_post_entity_died
on_pre_player_removed
on_pre_robot_exploded_cliff
on_robot_exploded_cliff
on_script_path_request_finished
on_surface_imported

Changed:
on_entity_died to return "loot"
on_player_crafted_item item_stack to allow editing the stack before it's put into the player inventory.
on_player_rotated_entity to return previous_direction

#### Of interest
Added LuaControl::character_running_speed read.
Added LuaFluidBox::get_prototype().
Added LuaForce::evolution_factor_by_pollution, evolution_factor_by_time, and evolution_factor_by_killing_spawners read/write.
Added LuaForce::index read.
Added LuaGameScript::autosave_enabled variable, that can be used to disable autosaving.
Added LuaGameScript::get_map_exchange_string().
Added LuaGameScript::get_player().
Added LuaGameScript::get_surface().
Added LuaGameScript::get_train_stops(), LuaSurface::get_train_stops(), and LuaForce::get_train_stops().
Added LuaGameScript::reload_mods().
Added LuaGameScript::styles read.
Added LuaGameScript::table_to_json() and LuaGameScript::json_to_table().
Added LuaLogisticNetwork::robots, construction_robots, logistic_robots read.
Added LuaPlayer::create_local_flying_text().
Added LuaPlayer::use_from_cursor().
Added runtime editable speed attribute to Unit.

#### Not of interest
Added LuaFlowStatistics::get_flow_count().
Added LuaForce::previous_research read/write.
Added LuaGameScript::auto_save().
Added LuaGameScript::disable_tutorial_triggers().
Added LuaGameScript::take_technology_screenshot().
Added LuaGroup::localised_name read.
Added LuaItemStack::deconstruct_area() and cancel_deconstruct_area().
Added LuaTransportLine::output_lines read.
Added support for hidden optional dependencies via '(?) mod-name'.
Added support for mods to change their own mod settings runtime.
Added support to run console commands in a specific mod context via: /c __mod-name__ *command*.
Added support to set quality when using LuaGameScript::take_screenshot.
Changed migration scripts so they run in the context of the mod that created them.
Lua scripts can now use require("__mod-name__.file") syntax.

#### Of interest
Added Entity prototype property "next_upgrade".
Added EnemySpawnerPrototype::min_darkness_to_spawn and max_darkness_to_spawn.
Added optional beam prototype properties random_end_animation_rotation and transparent_start_end_animations.
EnemySpawnerPrototype::result_units now supports any type of entity.
Added LuaEntityPrototype::next_upgrade read.

#### Not of interest
Added "fluid" energy_source type can be used for both fuel-value based fluids, and heat capacity based fluids configured the same was as the generator entity.
Added "if-else-chain" and "literal-boolean" noise expression types.
Added "spot-noise" noise function.
Added "void" energy_source type which makes any entity using the type not require power.
Added CraftingMachinePrototype::show_recipe_icon which changes if the recipe icon is shown in alt-mode.
Added DamageType::hidden.
~~Added Entity prototype flags "no-inserter-pickup" and "no-inserter-dropoff".~~ (See feb25th)
Added EntityPrototypeFlag "not-upgradable".
Added EquipmentGridPrototype::locked.
Added GeneratorPrototype::burner to allow making an entity that burns fuel and produces power.
Added LuaDamagePrototype::hidden read.
Added LuaEntityPrototype::automated_ammo_count read.
Added LuaEntityPrototype::cliff_explosive_prototype read.
Added LuaEntityPrototype::container_distance, belt_distance and belt_length read.
Added LuaEntityPrototype::darkness_for_all_lamps_on and darkness_for_all_lamps_off read.
Added LuaEntityPrototype::fluidbox_prototypes read.
Added LuaEntityPrototype::is_building read.
Added LuaEntityPrototype::min_darkness_to_spawn and max_darkness_to_spawn read.
Added LuaEntityPrototype::neighbour_bonus and neighbour_collision_increase read.
Added LuaEntityProtoype::draw_cargo read.
Added LuaEquipmentGridPrototype::background_color read.
Added LuaEquipmentGridPrototype::locked read.
Added LuaFluidPrototype::hidden read.
Added LuaItemPrototype::reload_time read.
Added LuaItemPrototype::robot_action read.
Added LuaItemPrototype::wire_count read.
Added LuaRecipePrototype::main_product read.
Added LuaTechnologyPrototype::hidden read.
Added ReactorPrototype::scale_energy_usage to allow making a heat source that stops consuming fuel when max temperature is reached.
Added ResourceEntityPrototype::randomize_visual_position.
Added SelectionToolPrototype flags "not-same-force", "friend", and "enemy".
Added SelectionToolPrototype optional filters: alt_entity_filters, alt_entity_type_filters, alt_tile_filters, alt_entity_filter_mode, and alt_tile_filter_mode.
Added SelectionToolPrototype optional filters: entity_filters, entity_type_filters, tile_filters, entity_filter_mode, and tile_filter_mode.
Added UnitPrototype::affected_by_tiles.
Added UnitPrototype::ai_settings, which allows overriding default biter behavior.
Added optional "min_working_temperature" and "default_temperature" to heat buffer prototype.
Added optional draw_cargo property to construction robot and logistic robot prototypes.
Added optional fluid prototype property "hidden".
Added optional fluid_product to production achievement prototypes.
Added optional technology prototype property "hidden".
Added rotation_speed value to Unit prototype.
Added support for arbitrary non-circular references to named noise expressions.
Added support to set draw_copper_wires and draw_circuit_wires for any entity that uses wires.
Added support to set wire_count on wires to define how many items are needed to connect 2 entities.
All autoplace controls are now available as noise expression variables.
AutoplaceSpecifications can now be defined in terms of probability_expression and richness_expression as an alternative to peaks.
Changed ElectricEnergyInterfacePrototype::enable_gui to gui_mode.
Changed ItemWithInventoryPrototype flag "when_manually_filtered" to "when-manually-filtered".
Changed LuaEntityPrototype::items_to_place_this and LuaTilePrototype::items_to_place_this to return an array of SimpleItemStack.
Changed ReactorPrototype::burner to ReactorPrototype::energy_source to allow heat sources with alternate energy types.
Changed SelectionToolPrototype flag "matches-force" to "same-force".
Changed TilePrototype::decorative_removal_probability default value to 0 (it was 1).
Changed radars so they support dynamic energy source types.
Recipes now support having no results by setting results = {}.
Removed the "default-" prefix from core NamedNoiseExpressions; property_expression_names in MapGenSettings simply override the expression named by the key.
energy_per_movement and energy_per_rotation of inserter is now specified in energy format (aka "5KJ") instead of just a number.
property_expression_name values can be numeric constants.

#### Added

defines.inventory.artillery_turret_ammo	
defines.inventory.artillery_wagon_ammo	
defines.command.stop	Stop moving and stay where you are.
defines.alert_type.train_out_of_fuel
defines.input_action.activate_copy	
defines.input_action.activate_cut	
defines.input_action.activate_paste
defines.input_action.admin_action	
defines.input_action.alternative_copy	
defines.input_action.cancel_upgrade	
defines.input_action.change_multiplayer_config	
defines.input_action.clear_selected_upgrade_item	
defines.input_action.clone_item	
defines.input_action.copy	
defines.input_action.delete_blueprint_library	
defines.input_action.import_permissions_string	
defines.input_action.map_editor_action	
defines.input_action.select_mapper_slot	
defines.input_action.select_next_valid_gun	
defines.input_action.set_heat_interface_mode	
defines.input_action.set_heat_interface_temperature	
defines.input_action.set_infinity_pipe_filter	
defines.input_action.switch_inserter_filter_mode_state
defines.input_action.toggle_map_editor	
defines.input_action.undo		
defines.input_action.upgrade	
defines.input_action.upgrade_opened_blueprint	
defines.gui_type.server_management	
defines.gui_type.player_management	

behavior_result
AI command exit status. See LuaEntity::set_command
defines.behavior_result.in_progress	
defines.behavior_result.fail	
defines.behavior_result.success	
defines.behavior_result.deleted	

flow_precision_index
defines.flow_precision_index.one_second	
defines.flow_precision_index.one_minute	
defines.flow_precision_index.ten_minutes	
defines.flow_precision_index.one_hour	
defines.flow_precision_index.ten_hours	
defines.flow_precision_index.fifty_hours	
defines.flow_precision_index.two_hundred_fifty_hours	
defines.flow_precision_index.one_thousand_hours	

entity_status
defines.entity_status.working	
defines.entity_status.no_power	
defines.entity_status.no_fuel	
defines.entity_status.no_recipe	
defines.entity_status.no_input_fluid	
defines.entity_status.no_research_in_progress	
defines.entity_status.no_minable_resources	
defines.entity_status.low_input_fluid	
defines.entity_status.low_power	
defines.entity_status.disabled_by_control_behavior	
defines.entity_status.disabled_by_script	
defines.entity_status.fluid_ingredient_shortage	
defines.entity_status.fluid_production_overload	
defines.entity_status.item_ingredient_shortage	
defines.entity_status.item_production_overload	
defines.entity_status.marked_for_deconstruction	
defines.entity_status.missing_required_fluid	
defines.entity_status.missing_science_packs	
defines.entity_status.waiting_for_source_items	
defines.entity_status.waiting_for_space_in_destination	

#### Removed

defines.inventory.player_tools
defines.input_action.select_gun	
defines.input_action.use_ability	

#### Omitted

Events and controllers previously mentioned.

## Changes in API but not changelog

- [x] LuaEntityPrototype removed: mining_power
- [x] LuaGameScript removed the `victorious_force` option from inside `set_game_state`
- [x] LuaItemPrototype removed attack_result, attack_range, build_distance_bonus, item_drop_distance_bonus, reach_distance_bonus, item_pickup_distance_bonus, loot_pickup_distance_bonus, resource_reach_distance_bonus
- [x] LuaRecipe removed catalysts
- [x] LuaStyle removed scaleable, selection_background_color, horizontal_scrollbar_spacing, vertical_scrollbar_spacing  added clicked_label_vertical_offset

### Feb 25th

Added Entity prototype flags "no-automated-item-removal" and "no-automated-item-insertion". (changed from previous)
Added LuaStyle::stretch_image_to_widget_size, only applies to "sprite" widget styles.
Added optional EntityPrototype::map_generator_bounding_box.
Added EntityPrototypeFlags "no-copy-paste" and "not-selectable-in-game".
Added ItemPrototypeFlags "only-in-cursor", "not-stackable", "can-extend-inventory", "primary-place-result" and "mod-openable".

- [x] Changed EnemySpawnerPrototype::result_units to support any type of entity.
- [x] Changed recipes to support having no results by setting results = {}.
- [x] Removed the "default-" prefix from core NamedNoiseExpressions; property_expression_names in MapGenSettings simply override the expression named by the key.
- [x] Removed ItemPrototypeFlags "goes-to-main-inventory" and "goes-to-quickbar".

Added on_pre_chunk_deleted and on_chunk_deleted events.
Added on_chart_tag_added, on_chart_tag_modified, and on_chart_tag_removed events.
Added LuaGameScript::set_wait_for_screenshots_to_finish().
Added LuaEntityPrototype::vision_distance read.
Added LuaPlayer::open_map(), zoom_to_world() and close_map().
Added LuaPlayer::render_mode read.
Added LuaPlayer::map_view_settings write.
Added LuaStyle::top_margin, right_margin, bottom_margin and left_margin read/write.
Added LuaStyle::use_header_filler, natural_width and natural_height read/write.
Added LuaStyle::extra_padding_when_activated read/write.
Added LuaStyle::extra_top_margin_when_activated, extra_bottom_margin_when_activated, extra_left_margin_when_activated and extra_right_margin_when_activated read/write.
Added LuaEntity::electric_network_id read.
Added LuaControl::character_additional_mining_categories read/write.
Added LuaGameScript::draw_resource_selection read/write.
Added LuaForce::get_hand_crafting_disabled_for_recipe() and set_hand_crafting_disabled_for_recipe().
Added LuaEntityPrototype::map_generator_bounding_box read.
Added LuaEntity::release_from_spawner().
Added on_cutscene_waypoint_reached, on_entity_cloned, on_area_cloned, on_marked_for_upgrade, on_cancelled_upgrade,
on_post_entity_died, on_pre_player_removed, on_pre_robot_exploded_cliff, on_robot_exploded_cliff,
on_script_path_request_finished, on_surface_imported, on_player_toggled_map_editor events.
Added LuaEntity::timeout read/write.
Added LuaEntity::highlight_box_type and highlight_box_blink_interval read/write.
Added LuaEntity::order_upgrade(), cancel_upgrade() and to_be_upgraded().
Added LuaEntity::research_queue_enabled read/write.
Added LuaGameScript::get_active_entities_count().
Added LuaGameScript::ticks_played read.
Added LuaGameScript::tick_paused and ticks_to_run read/write.
Added LuaItemPrototype::infinite read.
Added LuaItemStack::clear_upgrade_item(), get_mapper(), set_mapper().
Added LuaItemStack::is_upgrade_item read.
Added LuaLogisticCell::logistics_connection_distance read.
Added LuaLogisticNetwork::select_pickup_point() and select_drop_point().
Added LuaPlayer::jump_to_cutscene_waypoint().
Added LuaUnitGroup::group_number read.

- [x] Changed LuaEquipmentPrototype::energy_source to return a LuaElectricEnergySourcePrototype.
- [x] Removed LuaCustomChartTag::orientation and target.
- [x] Removed LuaFluidPrototype::pressure_to_speed_ratio and flow_to_energy_ratio.

### 0.17.0    

Added BeamPrototype::target_offset and random_target_offset.
Added TilePrototype::tint. Tile tint is packed to RGB 565 without alpha.
Added "mouse-cursor" definitions for overriding system mouse cursor in selection tools.
Increased limit for size of spritesheet to 8196px (regardless of sprite resolution settings). Maximal size of single sprite is 2048px in normal resolution and 4096px in high resolution. Smaller spritesheets can utilize parallel decompression better.
It's possible to specify "frame_sequence" in animation definition as array of frame numbers that should be played in given order.
Changed sound definition, so it can contain "aggregation" even when it doesn't contain "variations".
Renamed LuaEntity::get_infinity_filter(), set_infinity_filter(), and infinity_filters to get_infinity_container_filter(), set_infinity_container_filter(), and infinity_container_filters.

**Comment by mheguy** [comment]
`LuaSurface::find_entities/filtered now accepts a zero sized bounding box as "find everything that collides with this point".`
This makes all the checks for 0-area bounding boxes moot, right?

**Comment by plague006** [comment]
Addition: Added editor controller

**Comment by mheguy** [comment]
Did a search for each of the Prototype changes to make sure we didn't ref any of them.

**Comment by mheguy** [comment]
Factorio's `util` looks like it will include `insert_safe`. I'm curious what that is.

**Comment by theorangeangle** [comment]
From my basic comprehension, a lot of this will open the door for some fun scenarios 😄

**Comment by grilledham** [comment]
> `LuaSurface::find_entities/filtered now accepts a zero sized bounding box as "find everything that collides with this point".`
This makes all the checks for 0-area bounding boxes moot, right?

Yes and no, it depends on the logic in entity restrictions. For `danger_re_banned_entities` it returns true on empty bounding box, as it assumes this is from a bot. Of course we could move all bots into the white list, then I don't think we would need the check. Assuming there aren't other entities with zero size bounding box that the player can place.

**Comment by mheguy** [comment]
`serpent.block for 64bit keys` Thanks to Bilka for testing (windows machine running 0.17)
![image](https://user-images.githubusercontent.com/10162554/53359711-bb33de80-3901-11e9-98a7-e9334da84c1a.png)

**Comment by mheguy** [comment]
Updated with diff to 0.17.0 changelog

**Comment by mheguy** [comment]
Moved everything into https://github.com/Refactorio/RedMew/wiki/0.17-New-features-and-prototypes-to-tinker-with
