### ISSUE TITLE
Post 0.17 checklist

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#810]
- [x] Activate the webhook to redmew.com
- [x] Resume nightly releases
- [x] update luacheckrc

- [x] and a mental note to redo the info gui

- [x] water_none is now actually *no* water so we can check for instances where maps cleaned it up manually and remove them

**Comment by mheguy** [comment]
All tasks complete
