### ISSUE TITLE
[0.17] Rename /sc

### ISSUE THREAD

**Issue by Valansch** [Valansch/RedMew#817]
**Describe the bug**
/sc collides with vanilla /sc and cause an error during init.

**Expected behavior**
No error. :D

**Steps to reproduce**
Start scenario with 0.17

**Additional context**
Bilka:
>Since you guys are working hard on updating to 0.17 and I was made aware that it is important for your scenarios: In 0.17 the /silent-command has a /sc alias in vanilla. I was told that this conflicts with your commands and Plague isn't online so I hope it is okay that I let you know here.

I would not expect that we will be able to overwrite commands any time soon:

Valansch Today at 10:19 AM
>Any chance https://forums.factorio.com/viewtopic.php?f=28&t=64220 will ever be a thing?

Bilka Today at 10:20 AM
>I don't know, sorry.

**TODO**
- [x] Find new_name
- [x] Change `sc` in code to `new_name`
- [x] Add deprecated notice to `sc`
- [x] Change `sc` in docu to `new_name`
- [ ] Teach admins to no longer use `sc` and use `new_name` instead :)

**Comment by Valansch** [comment]
Any ideas for the new name? Maybe /save-command afterall?

**Comment by linaori** [comment]
`/sandbox`?

**Comment by Valansch** [comment]
What about those names?
- /terse-command
- /ts
- /quite-command
- /qc
- /discrete-command
- /dc
- /sandbox (Thanks lin)
- /sb
- /interface (I think thats what explosiv gaming named it)

**Comment by grilledham** [comment]
/command-silent
or /cs

I like /sb, /qc and /dc

**Comment by mheguy** [comment]
+1 for /sandbox and an alias of /sc

**Comment by Valansch** [comment]
But is it a sandbox?
I find that to be a bit misleading, because it's isolating anything. It's only redirecting errors.

**Comment by grilledham** [comment]
I've made an executive decision to rename `/sc` to `/dc` purely so we have something to merge when 0.17 lands.
We can change the name later if we want to.
#818

**Comment by Valansch** [comment]
Alright. I fixed the docu.

**Comment by mheguy** [comment]
Closed by #818
