### ISSUE TITLE
Diggy feedback/todo collection thread

### ISSUE THREAD

**Issue by linaori** [Valansch/RedMew#926]
With 0.17.x running a while and an increase of popularity, I want to create a collection of feedback/bugs etc so we can track things a bit better. If it has a link, there's an existing issue for it. If it's fixed/handled or not an issue, it will be checked.

### Bugs that affect Diggy
- [x] [2 Errors in retailer](https://github.com/Refactorio/RedMew/issues/879)
- [x] [Error in hail_hydra](https://github.com/Refactorio/RedMew/issues/878)
- [x] [diggy_cave_collapse: changes to on_built_tile](https://github.com/Refactorio/RedMew/issues/815)
- [x] [SimpleRoomGenerator water in Diggy corrupts stress levels](https://github.com/Refactorio/RedMew/issues/552)

### Wishlist
 - [ ] Replace room and terrain generation by the same system that generates ores
 - [ ] The ability to use the new render function to show (per player) what the stress levels are for a certain spot, this requires #552 to be fixed first as it would should incorrect data for some spots otherwise
 - [x] Ability to set enable/disable landfill via a config settings (fixed in #930)
 - [x] Ability to set the initial mining speed (fixed in #930)
 - [x] Merge the Diggy score table into the global score table by making it a simple storage so each scenario can do this
 - [ ] Make it possible to add custom columns (per scenario) to the player list to keep track of stats (makes #887 possible)
 - [x] Localization
 - [x] Localization of score table
 - [ ] [Cave Biomes](https://github.com/Refactorio/RedMew/issues/345)
 - [ ] [Diggy integration with existing mods (primarily Bobs + Angels)](https://github.com/Refactorio/RedMew/issues/301)
 - [ ] [Abandoned outposts(loot base)](https://github.com/Refactorio/RedMew/issues/245)
 - [ ] [Biter caves](https://github.com/Refactorio/RedMew/issues/244)
 - [x] Edit foreman advice on first rock mined, to include why rocks do not give stone.
 - [x] Biter performance late game might cause lag spikes (Partial solutions already implemented)
 - [ ] Ability to always show level and progress in a small window (Like the stats window)
 - [ ] Add something significant to rocket launches https://github.com/Refactorio/RedMew/issues/926#issuecomment-497214884
 - [x] Tweak oil spawn chances https://github.com/Refactorio/RedMew/issues/926#issuecomment-497210469 (fixed in #930)

**Comment by SimonFlapse** [comment]
~~Older issues related to Diggy:~~
~~#345~~
~~#301~~ 
~~#245~~
~~#244~~

~~Other feedback from Diggy project:~~
- [ ] ~~Edit foreman advice on first rock mined, to include why rocks do not give stone.~~
- [ ] ~~Biter performance late game might cause lag spikes (Partial solutions already implemented)~~
- [ ] ~~Ability to always show level and progress in a small window (Like the stats window)~~

**Comment by SReject** [comment]
Due to how generation works, a player can only select exposed rocks to deconstruct with bots/deconstruction blueprint. I suggest adding a feature to the radar that will generate the map within its range

**Comment by linaori** [comment]
@SimonFlapse I've updated the main post with what you've added

@SReject Do you have any idea how we could do that? As a soft-mod we can't alter anything in the base game, so we'd need an invisible entity that cannot be mined until it's reachable. To sum it up:
 - Current implementation is just a void tile with nothing on it
 - I'm not sure the base-game has an invisible item we can place for deconstruction
 - We can't prevent bots from flying into the void and mine stuff (though we could chain deconstruct if we have invisible entities marked)
 - Whenever a bot damages a rock, the internal mechanic that mimics mining will replace the rock with a new one (copy with less health), meaning any blueprints that were on the ground would get removed (at least in 0.16.x it did).

I'm not sure it's possible to implement this at the moment, or do you have any other ideas that might work?

**Comment by MulverineX** [comment]
Oil is verrry rare like to the point where it can take hours apon hours to just find one ore spot. Especially on a single to low player count save its seriously difficult to get your hands on an oil patch. After looking at the lua it looks like its a lot lower than all the other ores, in my opinion it should be raised up in both (if more in singleplayer) so that it is more realistic to get oil

**Comment by theorangeangle** [comment]
On rocket launch, something should happen to signify the player still being, well, in a cave. I had a couple of ideas:

- Rocks shakedown in a large area near the silo, possibly caving-in a weak spot near the silo if there is one.

- The brightness increases, possibly with each launch (signifying you have opened a hole in the cave to let light in)

- Biters spawn in spots near the silo, from "holes from the surface" you have opened up after disturbing the roof

**Comment by SimonFlapse** [comment]
> On rocket launch, something should happen to signify the player still being, well, in a cave. I had a couple of ideas:
> 
> * Rocks shakedown in a large area near the silo, possibly caving-in a weak spot near the silo if there is one.
> * The brightness increases, possibly with each launch (signifying you have opened a hole in the cave to let light in)
> * Biters spawn in spots near the silo, from "holes from the surface" you have opened up after disturbing the roof

Interesting ideas. 
This would also make solar panels work with each rocket giving them a minor power production increase. We could combine it with:
https://lua-api.factorio.com/latest/LuaSurface.html#LuaSurface.solar_power_multiplier to give solar panels an efficiency boost

**Comment by linaori** [comment]
@MulverineX the next release (and the current develop branch) have a fix for the oil spawn, it should be slightly higher now

**Comment by SReject** [comment]
Two prior discussed suggestions rolled into a single post:

- Config option(s) to set the initial evolution value and speed at which evolution increases  
- An added softmod command to (re)set biter evolution

**Comment by linaori** [comment]
@SReject I don't really want to change how the caching works for that particular mechanism, In #937 I've added 3 extra options should should make it possible to tweak the difficulty for new maps

**Comment by SReject** [comment]
> @SReject Do you have any idea how we could do that? As a soft-mod we can't alter anything in the base game, so we'd need an invisible entity that cannot be mined until it's reachable.  

The point of the radar suggestion is the expose the world beyond the layer of minable blocks. There would be no need for a void/mask block. Instead, the radar would generate and visibly expose the world beyond that which is currently reachable. Similar to how radar and sonar is used in geo-surveying to show whats under the ground so to speak.

**Comment by linaori** [comment]
Ah, so it would basically "mine" the void but leave rocks standing?

**Comment by theorangeangle** [comment]
side note - is it just me or is coal too difficult to find, early game?
we should probably increase the density in the sprinkle ore patches that spawn near market, and increase the % of coal in them. 


also it appears our oil balancing might have gone too far in the positive direction, both the public and some SP/co-op games report having a bit too much oil.

**Comment by SReject** [comment]
**Small Bug**:

When support- structures have an option to be replaced without deconstructing -- such as the case with walls being replaced with gates -- replacing them runs the routine to recalculate roof support without taking into account the new entity's support value.

What I think is happening is the recalculation is done twice:

0. Wall is removed  
1. Recalc  
2. Gate is placed  
3. Recalc  

Instead it should be:  

0. Wall is removed  
1. Before recalc, checked if wall is being replaced  
2. Gate is placed  
3. Recalc  

To reproduce:  

0. Add gates to the support structures list, making them equal to walls: `['gate'] = 3`  
1. Build two lines of walls with a space of 7 empty tiles between them  
2. Clear out the space between the wall lines  
3. Replace one line of walls with gates

**Comment by SReject** [comment]
**Suggestion:**

Add gates to to structure supports and have them equal to walls. This will greatly increase players' mobility when navigating builds. The price to manufacture manufacture means players would use walls for support while offering them a better choice for mobility

**Comment by SReject** [comment]
**Bug**

Your current oil patch code allows for spots to overlap in such a way that putting a pump jack on one blocks the others; this does not happen in vanilla.

![oilbug](https://user-images.githubusercontent.com/1975663/59154947-d60f0680-8a4b-11e9-8395-1eece93ffc00.png)

**Comment by linaori** [comment]
Not sure how we can fix the gate issue as they are separate events and don't know about each other. It also doesn't make sense to me to give gates a support value, as when they are open, they can't support the ceiling.

The oil thing might be fixable, but that code is kind of voodoo to me so if someone feels up to it, go for it! 😅

**Comment by TimvdLippe** [comment]
It would be great if the settings can be changed more easily to help single/couple of players. Youtube series I was following decided to stop for that reason: https://www.youtube.com/watch?v=wuNGeHkCXLI&t=720s We are facing the same with 3 people having to search for oil a lot (glad that is being addressed already!) as well as the ore patterns making it cumbersome to expand while keeping the factorio running.

**Comment by theorangeangle** [comment]
Idea: Tunnel boring machine

When the player has reached a mid/end game level with their XP (exact # TBD), tanks placed on the map will do higher damage to rocks. This would serve as a digging machine and the closest we can get to a FARL-style way of automating, as a different method compared to bots and hand mining.

**Comment by Claude477** [comment]
Added pull so get fixed 0.18.3 versions but need check out if working in solo
https://github.com/Refactorio/RedMew/pull/1032

**Comment by Ranakastrasz** [comment]
Started a new game with diggy, Version 0.17.79, no mods. No biters spawn. Default settings, cheated 1000x dig speed, and went significantly further than 40 tiles away.

I tried this before, and recall being eaten by biters, so I am not sure if I broke something or if the scenario is currently broken.

**Comment by SimonFlapse** [comment]
> Started a new game with diggy, Version 0.17.79, no mods. No biters spawn. Default settings, cheated 1000x dig speed, and went significantly further than 40 tiles away.
> 
> I tried this before, and recall being eaten by biters, so I am not sure if I broke something or if the scenario is currently broken.

@Ranakastrasz 

Are you saying that disabling biters doesn't work? Where did you disable them?

**Comment by Ranakastrasz** [comment]
I am saying that I didn't mess with any settings and no biters spawned, even after I went significantly further than the 48 tiles away from spawn. I had disabled pollution, but reenabled it with a command after it failed to spawn any biters, no change.
edit: Now that I am properly using the latest (0.18) version of factorio, I have now managed to be eaten by biters. So the issue is fixed.

**Comment by Ranakastrasz** [comment]
In addition to Cave Biomes, I could imagine lakes (give normal/deep water, and give such a stability value like rock). Lit areas. (not sure if you can produce light without custom entities) which have an opening to the ceiling, and hence solar panels work there. (maybe required for rocket placement?)

Walls/floor removal undoes itself once (and becomes invulnerable for a second) if it would cause a collapse. Or requires a full second to mine regardless of mining power (if possible)

But, well, there are a lot of things you could potentially add.
