### ISSUE TITLE
Crash Site Feedback/todo collection thread 

### ISSUE THREAD

**Issue by theorangeangle** [Valansch/RedMew#957]
Similar to our Diggy feedback issue, we have accumulated a lot of feedback on Crash Site since the last major updates. With autofill being added scenario-wide, it might be time to add some new features and fix existing "exploits" that break the game balance a little.

**Bugs, Refactoring and Balance Issues**
- [ ] Keeping one turret alive at an outpost keeps it relatively defended from biter pathfinding
- [x] Shooting a power pole at an outpost makes destroying the laser turrets much easier( _fixed by #959_)
- [ ] Late-game is too easy after MK2 armor
- [ ] ~~Hail Hydra [causes lag issues](https://clips.twitch.tv/CleanAverageCheeseArsonNoSexy) when nuking spawners (late-game spawner clearing)~~
- [ ] Rename the different crash site modes as "biomes" or "planets".

**Wishlist/Suggested Ideas**

- [x] Spawn combat robots in late-game outposts as a defense mechanism (#659)
- [ ] More random events in general
- [ ] Change the furnace at spawn to a damaged assembler if possible?  
  - Cause all outpost to pause production for x time to add a bit of a resource crunch
  - A popup shows up saying "the rocket is falling back to earth. abort mission!" and then random artillery strikes start happening in the base
  - "Supply Drops" with the wreckage item
- [ ] Respawn timer shouldn't be as long or maybe timer starts off small and increases per death or maybe based off evolution
- [ ] Decrease the timer for refilling outpost turrets, notably flamethrower turrets
- [ ] New outposts that are different than the standard "wall with assembler or chest", notably some suggested by [Naquada](https://discordapp.com/channels/432567222481846283/478339417245876256/571808225880440844)
- [ ] More coins in the one-off "loot" outposts
- [x] An option in the market to "reveal" an outpost with a map marker and/or chunk reveal
- [x] Vote-restart, win condition, or some semi-automated way of restarting the map
- [ ] Making assemblers destructible once the outpost is captured 
- [ ] Not allowing assemblers to operate without the outpost captured
- [ ] Some balancing for if the person is in SP/ an option in the config to set an "easy" mode to give solo/co-op players a fighting chance 
- [x] Add cutscene tutorial for joining the game the first time, similar to Diggy.

**Jayefuu's To Do list:**
- [ ] Make nuclear outposts harder to capture by changing the turrets to a different type/mix
- [ ] Balance spy so players don't just use strike instead. Make it cheaper or make the first strike upgrade more expensive.
- [ ] Fix artillery pickup bot spawn exploits (in progress)
- [ ] Work on accessibility "ping" to get attention of players with no game sounds on/accessible
- [ ] Enemy spider patrols
- [ ] Rocket tanks!
- [ ] Find a way to make more coins accessible.

**Comment by grilledham** [comment]
I don't know if the issue is resolved or the situation is different. But we used nukes recently on crashsite to clear up biters and I don't remember problems with lag. And if there is an issue with nukes, it's unlikely we would be able to do anything about it. So I'm going to cross that one off.

**Comment by theorangeangle** [comment]
**Crashsite Cutscene Ideas**
- Tutorial at map start showing what an outpost is, how to get and use coins, and how outposts work. (Might want to do on second, identical surface? Someone on discord brought up the issue of necessity points in the cutscene being destructible
- Zoom in (and pause for any attacks that might be occurring?) at an outpost when it is captured 
- Show when the next biter evolution has occurred (and demonstrate hail hydra) with a zoom in 
- When an outpost is upgraded, text runs across the screen of the new prices/faster item speed

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Zahir-Khan** [comment]
Players are consistently reporting late game to be boring. We should give them something that they can do to finish the game quicker. 
For example, I was thinking to add a special item buy at the spawn market for 100k coins. It will increase the arty range research (lvl 9) to cover the whole map without the tedious work required to build turrets columns.
We could also add a similar upgrade to increase the laser turret damage to vanilla levels. 
Another item to increase tank shell damage to encourage more player combat.

Open to more ideas that focus on late-game additions.

**Comment by MommyTigress** [comment]
1. Nuclear outposts are highly sought out and are under protected currently - just gun turrets. 
2. A list of available commands (and what they do) for players should be added.
3. Moderators need to be pinged when a report is received.
4. Cost of spy needs to be adjusted. 
5. Tagging a player such as Jayefuu# supposedly makes a sound, but that's not hearing disability accessible.
6. Enemy spiders?
7. It was discussed before about preventing free power from enemy outposts to make the game harder - force players to pollute. 
8. New idea - since coins are becoming more desired for upgrades and such. What about small outpost spawns that are just boxes of coins?

**Comment by Jayefuu** [comment]
Thanks @MommyTigress I've added the above issues to the Issue.
