### ISSUE TITLE
Space Race feedback/todo collection thread

### ISSUE THREAD

**Issue by SimonFlapse** [Valansch/RedMew#996]
Opened to keep track of feedback for Space Race.

Todo:

Critical:

- [ ] Team Colors
- [ ] Bug fix for silo spawn
- [ ] Spectator mode

Market:
- [x] Add repair pack to market
- [x] Increase fish price
- [x] Increase science prices in market
- [x] Allow buying random research from the market
- [x] Drop coins when player killed by turret (Only half or less)
- [ ] Artillery turrets on either side of the rocket silo + Artillery Ammo in market + Remote

Research:
- [ ] Land Mines

Other:
- [x] Enemy wood chests minable (If possible)
- [x] Safe Zone limited area
- [x] Research queue enabled
- [x] Coins not counted when inserted, only when picked up
- [x] Increased coin drop for strategic entities
- [x] Beach like transition between land and shallow water
- [x] Cliffs around rocket silo
- [x] set_tiles for the ditch to prevent "cheating" the map gen
- [ ] GUI button for /warp
- [ ] More biters (Not fixed, can be tweaked before generating the map)

Future:
- [x] Three outposts in the shallow water (For each of the three parts required for rocket parts)
- [ ] Islands in the shallow water
- [ ] Multiple markets for different types of items to prevent a cluttered market
- [x] Equal ores
- [ ] Toggle player lights (flashlight) when in war zone
- [ ] Cutscene that plays when pvp zone opens, explaining the map. 

Moderation:
- [ ] /watch enabled for admins
- [ ] /info command to open the map info tab GUI
- [ ] /SRversion command to open the extra info GUI

Ideas:

- [ ] Tank cannons only available in market
- [ ] Unlock research for other team after X minutes, to prevent snowballing ([details](https://github.com/Refactorio/RedMew/pull/993#issuecomment-557836700)
- [ ] Auto restart
- [ ] Weapon balance

**Comment by SimonFlapse** [comment]
Second play through feedback (2019-10-27):

- [ ] Waiting gui timer jumps serveral minutes when game is starting
- [x] Gun turrets active time is too quick
- [ ] Team list
- [ ] Spectate
- [ ] Market unlocks are hard to understand/unlock (Show progress)
- [ ] Market bug UFW market not unlocking walls / UFE not unlocking military

- [ ] Random sciences can be brought after last research in that tier has been researched
- [ ] You are able to kill friendly entities and get coins
- [ ] Force colors (Red and Blue)
- [ ] Global alert for rocket progress

- [ ] Count down after winning before returning to snake

**Comment by SIGSTACKFAULT** [comment]
Once one team gains a foothold, the other team is basically screwed.

- [ ] implement a _negative_ feedback loop.
